//! Test-only helpers. Compiled out of release builds.
//!
//! Assets here are generated by this file rather than checked in, so the repository
//! carries no third-party binary of unclear provenance.

/// A valid 1x1 PNG, assembled byte by byte with a locally computed CRC-32.
pub fn minimal_png() -> Vec<u8> {
    let mut v = vec![0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A];
    // IHDR: 1x1, 8-bit, colour type 2 (truecolour)
    push_chunk(
        &mut v,
        &[
            b'I', b'H', b'D', b'R', 0, 0, 0, 1, 0, 0, 0, 1, 8, 2, 0, 0, 0,
        ],
    );
    // IDAT: one zlib-wrapped scanline
    push_chunk(
        &mut v,
        &[
            b'I', b'D', b'A', b'T', 0x08, 0x1D, 0x63, 0x60, 0x60, 0x60, 0x00, 0x00, 0x00, 0x04,
            0x00, 0x01,
        ],
    );
    push_chunk(&mut v, b"IEND");
    v
}

fn push_chunk(v: &mut Vec<u8>, body: &[u8]) {
    let len = (body.len() - 4) as u32;
    v.extend_from_slice(&len.to_be_bytes());
    v.extend_from_slice(body);
    v.extend_from_slice(&crc32(body).to_be_bytes());
}

fn crc32(data: &[u8]) -> u32 {
    let mut crc = 0xFFFF_FFFFu32;
    for b in data {
        crc ^= *b as u32;
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                (crc >> 1) ^ 0xEDB8_8320
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

#[cfg(test)]
mod tests {
    #[test]
    fn the_generated_png_actually_decodes() {
        // If this fails, every image test in the crate is testing nothing.
        let img =
            image::load_from_memory(&super::minimal_png()).expect("generated PNG must decode");
        assert_eq!(img.width(), 1);
        assert_eq!(img.height(), 1);
    }
}
