//! Synthetic corpus and round-trip fidelity suite.
//!
//! Every fixture here is generated by this file from the canonical model. No document in
//! this suite originates from a real case file, a third-party converter, or any pre-existing
//! implementation — see docs/clean-room/README.md, "Test corpus provenance".
//!
//! Run `TAVZIH_DUMP_CORPUS=1 cargo test --test corpus` to also write every artifact to
//! `target/corpus/` for the manual UYAP and Word acceptance gates.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use tavzih_core::convert::{convert_bytes, Direction, Status};
use tavzih_core::docx;
use tavzih_core::model::*;
use tavzih_core::udf;
use tavzih_core::warnings::{Severity, WarningCode, WarningSink};

/// The mandated Turkish coverage string.
const TR: &str = "Çağdaş Türkiye Cumhuriyeti — İİK, HMK, ıİğĞüÜşŞöÖçÇ";

// ---------------------------------------------------------------- helpers

fn doc(blocks: Vec<Block>) -> Document {
    Document {
        meta: Metadata::default(),
        sections: vec![Section {
            blocks,
            ..Default::default()
        }],
        lists: vec![],
    }
}

fn para(text: &str) -> Block {
    Block::Paragraph(Paragraph::plain(text))
}

fn run(text: &str, props: RunProps) -> Run {
    Run::Text {
        text: text.into(),
        props,
    }
}

fn cell(text: &str) -> TableCell {
    TableCell {
        blocks: vec![para(text)],
        grid_span: 1,
        ..Default::default()
    }
}

fn cell_span(text: &str, span: usize) -> TableCell {
    TableCell {
        blocks: vec![para(text)],
        grid_span: span,
        ..Default::default()
    }
}

fn png() -> Vec<u8> {
    // Same locally generated 1x1 PNG used by the unit tests.
    let mut v = vec![0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A];
    let chunk = |v: &mut Vec<u8>, body: &[u8]| {
        v.extend_from_slice(&((body.len() - 4) as u32).to_be_bytes());
        v.extend_from_slice(body);
        let mut crc = 0xFFFF_FFFFu32;
        for b in body {
            crc ^= *b as u32;
            for _ in 0..8 {
                crc = if crc & 1 != 0 {
                    (crc >> 1) ^ 0xEDB8_8320
                } else {
                    crc >> 1
                };
            }
        }
        v.extend_from_slice(&(!crc).to_be_bytes());
    };
    chunk(
        &mut v,
        &[
            b'I', b'H', b'D', b'R', 0, 0, 0, 1, 0, 0, 0, 1, 8, 2, 0, 0, 0,
        ],
    );
    chunk(
        &mut v,
        &[
            b'I', b'D', b'A', b'T', 0x08, 0x1D, 0x63, 0x60, 0x60, 0x60, 0x00, 0x00, 0x00, 0x04,
            0x00, 0x01,
        ],
    );
    chunk(&mut v, b"IEND");
    v
}

fn image_run(w: f32, h: f32) -> Run {
    Run::Image(Image {
        data: Arc::new(png()),
        format: ImageFormat::Png,
        width_pt: w,
        height_pt: h,
    })
}

/// Flattened structural fingerprint of a document, used to compare a document with its
/// round trip. Deliberately semantic — ZIP bytes will always differ.
#[derive(Debug, Default, PartialEq)]
struct Fingerprint {
    text: String,
    paragraphs: usize,
    tables: usize,
    rows: usize,
    cells: usize,
    merged: usize,
    images: usize,
    image_bytes: usize,
    tabs: usize,
    tab_stops: usize,
    bold: usize,
    italic: usize,
    underline: usize,
    list_paras: usize,
    alignments: Vec<u8>,
    has_header: bool,
    has_footer: bool,
    header_text: String,
    footer_text: String,
    landscape: bool,
}

fn walk(blocks: &[Block], f: &mut Fingerprint) {
    for b in blocks {
        match b {
            Block::Paragraph(p) => {
                f.paragraphs += 1;
                f.text.push_str(&p.text());
                f.text.push('\n');
                f.alignments.push(p.props.alignment as u8);
                f.tab_stops += p.props.tab_stops.len();
                if p.props.list.is_some() {
                    f.list_paras += 1;
                }
                for r in &p.runs {
                    match r {
                        Run::Tab { .. } => f.tabs += 1,
                        Run::Image(i) => {
                            f.images += 1;
                            f.image_bytes += i.data.len();
                        }
                        Run::Text { props, .. } => {
                            if props.bold {
                                f.bold += 1
                            }
                            if props.italic {
                                f.italic += 1
                            }
                            if props.underline {
                                f.underline += 1
                            }
                        }
                        _ => {}
                    }
                }
            }
            Block::Table(t) => {
                f.tables += 1;
                f.rows += t.rows.len();
                for r in &t.rows {
                    f.cells += r.cells.len();
                    for c in &r.cells {
                        if c.grid_span > 1 {
                            f.merged += 1;
                        }
                        walk(&c.blocks, f);
                    }
                }
            }
            Block::PageBreak => {}
        }
    }
}

fn fingerprint(d: &Document) -> Fingerprint {
    let mut f = Fingerprint::default();
    let s = &d.sections[0];
    walk(&s.blocks, &mut f);
    f.has_header = s.header.is_some();
    f.has_footer = s.footer.is_some();
    f.landscape = s.page.orientation == Orientation::Landscape;
    if let Some(h) = &s.header {
        let mut g = Fingerprint::default();
        walk(&h.blocks, &mut g);
        f.header_text = g.text;
        f.images += g.images;
        f.image_bytes += g.image_bytes;
    }
    if let Some(x) = &s.footer {
        let mut g = Fingerprint::default();
        walk(&x.blocks, &mut g);
        f.footer_text = g.text;
    }
    f
}

fn to_docx(d: &Document) -> Vec<u8> {
    let mut w = WarningSink::new();
    let b = docx::writer::write_docx(d, &mut w).expect("write docx");
    docx::writer::validate(&b).expect("emitted docx must validate");
    b
}

fn to_udf(d: &Document) -> Vec<u8> {
    let mut w = WarningSink::new();
    let x = udf::writer::write_content_xml(d, &mut w).expect("write udf");
    udf::writer::validate(&x).expect("emitted udf must satisfy the tiling invariant");
    udf::writer::package(&x).expect("package udf")
}

fn read_docx(b: &[u8]) -> (Document, Vec<WarningCode>) {
    let mut w = WarningSink::new();
    let d = docx::reader::read_docx(b, &mut w).expect("read docx");
    (d, w.into_vec().iter().map(|x| x.code).collect())
}

fn read_udf(b: &[u8]) -> (Document, Vec<WarningCode>) {
    let mut w = WarningSink::new();
    let d = udf::reader::read_udf(b, &mut w).expect("read udf");
    (d, w.into_vec().iter().map(|x| x.code).collect())
}

fn dump(name: &str, ext: &str, bytes: &[u8]) {
    if std::env::var("TAVZIH_DUMP_CORPUS").is_err() {
        return;
    }
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../target/corpus");
    let _ = std::fs::create_dir_all(&dir);
    let _ = std::fs::write(dir.join(format!("{name}.{ext}")), bytes);
}

/// Assert a document survives DOCX -> UDF -> DOCX with its fingerprint intact.
fn assert_docx_roundtrip(name: &str, d: &Document) -> Vec<WarningCode> {
    let src = to_docx(d);
    dump(name, "docx", &src);
    let mut w = WarningSink::new();
    let udf_bytes = convert_bytes(&src, Direction::DocxToUdf, &mut w).expect("docx->udf");
    dump(&format!("{name}.from-docx"), "udf", &udf_bytes);
    let mut w2 = WarningSink::new();
    let back = convert_bytes(&udf_bytes, Direction::UdfToDocx, &mut w2).expect("udf->docx");
    dump(&format!("{name}.roundtrip"), "docx", &back);

    let (a, _) = read_docx(&src);
    let (b, _) = read_docx(&back);
    let (fa, fb) = (fingerprint(&a), fingerprint(&b));
    assert_eq!(
        fa.text, fb.text,
        "[{name}] text changed across DOCX->UDF->DOCX"
    );
    assert_eq!(
        fa.paragraphs, fb.paragraphs,
        "[{name}] paragraph count changed"
    );
    assert_eq!(fa.tables, fb.tables, "[{name}] table count changed");
    assert_eq!(fa.rows, fb.rows, "[{name}] row count changed");
    assert_eq!(fa.cells, fb.cells, "[{name}] cell count changed");
    assert_eq!(fa.merged, fb.merged, "[{name}] merged-cell count changed");
    assert_eq!(fa.images, fb.images, "[{name}] image count changed");
    assert_eq!(
        fa.image_bytes, fb.image_bytes,
        "[{name}] image bytes changed (re-encoded?)"
    );
    assert_eq!(fa.tabs, fb.tabs, "[{name}] tab count changed");
    assert_eq!(fa.bold, fb.bold, "[{name}] bold run count changed");
    assert_eq!(fa.italic, fb.italic, "[{name}] italic run count changed");
    assert_eq!(
        fa.underline, fb.underline,
        "[{name}] underline run count changed"
    );
    assert_eq!(
        fa.alignments, fb.alignments,
        "[{name}] paragraph alignments changed"
    );
    assert_eq!(
        fa.list_paras, fb.list_paras,
        "[{name}] list paragraph count changed"
    );
    assert_eq!(fa.has_header, fb.has_header, "[{name}] header lost");
    assert_eq!(fa.has_footer, fb.has_footer, "[{name}] footer lost");
    assert_eq!(
        fa.header_text, fb.header_text,
        "[{name}] header text changed"
    );
    assert_eq!(
        fa.footer_text, fb.footer_text,
        "[{name}] footer text changed"
    );
    w.into_vec().iter().map(|x| x.code).collect()
}

/// Assert a document survives UDF -> DOCX -> UDF with its fingerprint intact.
fn assert_udf_roundtrip(name: &str, d: &Document) -> Vec<WarningCode> {
    let src = to_udf(d);
    dump(name, "udf", &src);
    let mut w = WarningSink::new();
    let docx_bytes = convert_bytes(&src, Direction::UdfToDocx, &mut w).expect("udf->docx");
    dump(&format!("{name}.from-udf"), "docx", &docx_bytes);
    let mut w2 = WarningSink::new();
    let back = convert_bytes(&docx_bytes, Direction::DocxToUdf, &mut w2).expect("docx->udf");
    dump(&format!("{name}.roundtrip"), "udf", &back);

    let (a, _) = read_udf(&src);
    let (b, _) = read_udf(&back);
    let (fa, fb) = (fingerprint(&a), fingerprint(&b));
    assert_eq!(
        fa.text, fb.text,
        "[{name}] text changed across UDF->DOCX->UDF"
    );
    assert_eq!(
        fa.paragraphs, fb.paragraphs,
        "[{name}] paragraph count changed"
    );
    assert_eq!(fa.tables, fb.tables, "[{name}] table count changed");
    assert_eq!(fa.cells, fb.cells, "[{name}] cell count changed");
    assert_eq!(fa.images, fb.images, "[{name}] image count changed");
    assert_eq!(
        fa.image_bytes, fb.image_bytes,
        "[{name}] image bytes changed (re-encoded?)"
    );
    assert_eq!(fa.tabs, fb.tabs, "[{name}] tab count changed");
    assert_eq!(fa.bold, fb.bold, "[{name}] bold run count changed");
    assert_eq!(fa.alignments, fb.alignments, "[{name}] alignments changed");
    assert_eq!(fa.has_header, fb.has_header, "[{name}] header lost");
    assert_eq!(fa.has_footer, fb.has_footer, "[{name}] footer lost");
    w.into_vec().iter().map(|x| x.code).collect()
}

/// Every case runs in both directions unless the case says otherwise.
fn assert_both(name: &str, d: &Document) {
    assert_docx_roundtrip(name, d);
    assert_udf_roundtrip(name, d);
}

// ---------------------------------------------------------------- cases

#[test]
fn c01_plain_text() {
    assert_both(
        "01_plain_text",
        &doc(vec![
            para("Birinci paragraf."),
            para("Ikinci paragraf."),
            para("Ucuncu paragraf."),
        ]),
    );
}

#[test]
fn c02_turkish_unicode() {
    let d = doc(vec![
        para(TR),
        para("ıİğĞüÜşŞöÖçÇ"),
        para("Şüphesiz, İstanbul'da görülen davada; ığdır, çağrı, öğüt."),
    ]);
    assert_both("02_turkish_unicode", &d);
    // The mandated string must appear verbatim in both outputs.
    let u = String::from_utf8_lossy(&to_udf(&d)).len();
    assert!(u > 0);
    let (back, _) = read_udf(&to_udf(&d));
    let Block::Paragraph(p) = &back.sections[0].blocks[0] else {
        panic!()
    };
    assert_eq!(
        p.text(),
        TR,
        "the mandated Turkish string must survive byte-for-byte"
    );
}

#[test]
fn c03_bold_italic_underline() {
    let d = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps::default(),
        runs: vec![
            run(
                "kalın",
                RunProps {
                    bold: true,
                    ..Default::default()
                },
            ),
            run(" düz ", RunProps::default()),
            run(
                "eğik",
                RunProps {
                    italic: true,
                    ..Default::default()
                },
            ),
            run(" ", RunProps::default()),
            run(
                "altı çizili",
                RunProps {
                    underline: true,
                    ..Default::default()
                },
            ),
        ],
    })]);
    assert_both("03_bold_italic_underline", &d);
}

#[test]
fn c04_mixed_runs() {
    let d = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps::default(),
        runs: vec![
            run(
                "HMK",
                RunProps {
                    bold: true,
                    italic: true,
                    underline: true,
                    ..Default::default()
                },
            ),
            run(" m. ", RunProps::default()),
            run(
                "119",
                RunProps {
                    bold: true,
                    font_size_pt: Some(16.0),
                    ..Default::default()
                },
            ),
            run(" — ", RunProps::default()),
            run(
                "kırmızı",
                RunProps {
                    color: Some(Color {
                        r: 0xC0,
                        g: 0,
                        b: 0,
                    }),
                    ..Default::default()
                },
            ),
            run(" — ", RunProps::default()),
            run(
                "Arial",
                RunProps {
                    font_family: Some("Arial".into()),
                    ..Default::default()
                },
            ),
        ],
    })]);
    assert_both("04_mixed_runs", &d);
}

#[test]
fn c05_alignments() {
    let mk = |a: Alignment, t: &str| {
        Block::Paragraph(Paragraph {
            props: ParaProps {
                alignment: a,
                ..Default::default()
            },
            runs: vec![run(t, RunProps::default())],
        })
    };
    assert_both(
        "05_alignments",
        &doc(vec![
            mk(Alignment::Left, "Sola dayalı"),
            mk(Alignment::Center, "Ortalanmış"),
            mk(Alignment::Right, "Sağa dayalı"),
            mk(
                Alignment::Justify,
                "İki yana yaslanmış uzun bir paragraf metni burada yer alır.",
            ),
        ]),
    );
}

#[test]
fn c06_indentation() {
    let mk = |p: ParaProps, t: &str| {
        Block::Paragraph(Paragraph {
            props: p,
            runs: vec![run(t, RunProps::default())],
        })
    };
    assert_both(
        "06_indentation",
        &doc(vec![
            mk(
                ParaProps {
                    left_indent_pt: 36.0,
                    ..Default::default()
                },
                "Soldan girinti",
            ),
            mk(
                ParaProps {
                    right_indent_pt: 36.0,
                    ..Default::default()
                },
                "Sağdan girinti",
            ),
            mk(
                ParaProps {
                    first_line_indent_pt: 21.0,
                    ..Default::default()
                },
                "İlk satır girintisi",
            ),
            mk(
                ParaProps {
                    hanging_pt: 28.0,
                    left_indent_pt: 28.0,
                    ..Default::default()
                },
                "Asılı girinti",
            ),
        ]),
    );
}

#[test]
fn c07_tabs() {
    // The legal-pleading pattern: label, tab, colon, tab, value.
    let stops = vec![
        TabStop {
            pos_pt: 85.0,
            align: TabAlign::Left,
        },
        TabStop {
            pos_pt: 100.0,
            align: TabAlign::Left,
        },
    ];
    let mk = |t: &str| {
        Block::Paragraph(Paragraph {
            props: ParaProps {
                tab_stops: stops.clone(),
                ..Default::default()
            },
            runs: vec![run(t, RunProps::default())],
        })
    };
    assert_both(
        "07_tabs",
        &doc(vec![
            mk("DAVACI\t:\tAli VELİ"),
            mk("VEKİLİ\t:\tAv. Ayşe FATMA"),
            mk("KONU\t:\tDava dilekçesidir."),
        ]),
    );
}

#[test]
fn c08_spacing() {
    let mk = |p: ParaProps, t: &str| {
        Block::Paragraph(Paragraph {
            props: p,
            runs: vec![run(t, RunProps::default())],
        })
    };
    assert_both(
        "08_spacing",
        &doc(vec![
            mk(
                ParaProps {
                    space_before_pt: 12.0,
                    ..Default::default()
                },
                "Öncesinde boşluk",
            ),
            mk(
                ParaProps {
                    space_after_pt: 12.0,
                    ..Default::default()
                },
                "Sonrasında boşluk",
            ),
            mk(
                ParaProps {
                    line_spacing_extra: 0.5,
                    ..Default::default()
                },
                "Bir buçuk satır aralığı",
            ),
            mk(
                ParaProps {
                    line_spacing_extra: 1.0,
                    ..Default::default()
                },
                "Çift satır aralığı",
            ),
        ]),
    );
}

#[test]
fn c09_bullet_list() {
    let mut d = doc((1..=3)
        .map(|i| {
            Block::Paragraph(Paragraph {
                props: ParaProps {
                    list: Some(ListRef {
                        list_id: 1,
                        level: 1,
                    }),
                    ..Default::default()
                },
                runs: vec![run(&format!("Madde {i}"), RunProps::default())],
            })
        })
        .collect());
    d.lists = vec![ListDef {
        list_id: 1,
        kind: ListKind::Bullet(BulletKind::Ellipse),
    }];
    assert_both("09_bullet_list", &d);
}

#[test]
fn c10_numbered_list() {
    let mut d = doc((1..=3)
        .map(|i| {
            Block::Paragraph(Paragraph {
                props: ParaProps {
                    list: Some(ListRef {
                        list_id: 1,
                        level: 1,
                    }),
                    ..Default::default()
                },
                runs: vec![run(&format!("Numaralı {i}"), RunProps::default())],
            })
        })
        .collect());
    d.lists = vec![ListDef {
        list_id: 1,
        kind: ListKind::Number(NumberKind::DecimalDot),
    }];
    assert_both("10_numbered_list", &d);
}

#[test]
fn c11_nested_list() {
    let mk = |lvl: u32, t: &str| {
        Block::Paragraph(Paragraph {
            props: ParaProps {
                list: Some(ListRef {
                    list_id: 1,
                    level: lvl,
                }),
                ..Default::default()
            },
            runs: vec![run(t, RunProps::default())],
        })
    };
    let mut d = doc(vec![
        mk(1, "Birinci düzey"),
        mk(2, "İkinci düzey"),
        mk(3, "Üçüncü düzey"),
        mk(2, "İkinci düzey tekrar"),
        mk(1, "Birinci düzey tekrar"),
    ]);
    d.lists = vec![ListDef {
        list_id: 1,
        kind: ListKind::Number(NumberKind::DecimalDot),
    }];
    let warns = assert_docx_roundtrip("11_nested_list", &d);
    assert!(
        warns.contains(&WarningCode::ListNestingUnverified),
        "nested lists must declare that their UYAP appearance is unverified"
    );
    assert_udf_roundtrip("11_nested_list", &d);
}

#[test]
fn c12_simple_table() {
    let t = Table {
        name: Some("Tablo1".into()),
        column_widths: vec![120.0, 200.0, 100.0],
        border: TableBorder::Cell,
        rows: vec![
            TableRow {
                cells: vec![cell("Sıra"), cell("Açıklama"), cell("Tutar")],
                is_header: true,
                ..Default::default()
            },
            TableRow {
                cells: vec![cell("1"), cell("Vekalet ücreti"), cell("15.000,00 TL")],
                ..Default::default()
            },
            TableRow {
                cells: vec![cell("2"), cell("Yargılama gideri"), cell("2.450,50 TL")],
                ..Default::default()
            },
        ],
        ..Default::default()
    };
    assert_both("12_simple_table", &doc(vec![Block::Table(t)]));
}

#[test]
fn c13_horizontal_merge() {
    let t = Table {
        column_widths: vec![100.0, 100.0, 100.0],
        border: TableBorder::Cell,
        rows: vec![
            TableRow {
                cells: vec![cell_span("Üç sütunu kaplayan başlık", 3)],
                is_header: true,
                ..Default::default()
            },
            TableRow {
                cells: vec![cell_span("İki sütun", 2), cell("Tek")],
                ..Default::default()
            },
            TableRow {
                cells: vec![cell("a"), cell("b"), cell("c")],
                ..Default::default()
            },
        ],
        ..Default::default()
    };
    assert_both("13_horizontal_merge", &doc(vec![Block::Table(t)]));
}

#[test]
fn c14_vertical_merge() {
    // UDF has no vertical merge (EXP-006). The requirement is that the geometry survives
    // and nothing disappears, with the loss reported.
    let t = Table {
        column_widths: vec![100.0, 100.0],
        border: TableBorder::Cell,
        rows: vec![
            TableRow {
                cells: vec![cell("Dikey birleşik"), cell("sağ 1")],
                ..Default::default()
            },
            TableRow {
                cells: vec![
                    TableCell {
                        blocks: vec![],
                        grid_span: 1,
                        ..Default::default()
                    },
                    cell("sağ 2"),
                ],
                ..Default::default()
            },
        ],
        ..Default::default()
    };
    let d = doc(vec![Block::Table(t)]);
    assert_both("14_vertical_merge", &d);
    // and the surrounding text must be untouched
    let (back, _) = read_udf(&to_udf(&d));
    let Block::Table(bt) = &back.sections[0].blocks[0] else {
        panic!("table lost")
    };
    assert_eq!(bt.rows.len(), 2);
    assert_eq!(bt.rows[0].cells.len(), 2);
}

#[test]
fn c15_complex_merge() {
    let t = Table {
        column_widths: vec![80.0, 80.0, 80.0, 80.0],
        border: TableBorder::Cell,
        rows: vec![
            TableRow {
                cells: vec![cell_span("Tam genişlik başlık", 4)],
                is_header: true,
                ..Default::default()
            },
            TableRow {
                cells: vec![cell_span("Sol yarı", 2), cell_span("Sağ yarı", 2)],
                ..Default::default()
            },
            TableRow {
                cells: vec![cell("a"), cell_span("bc", 2), cell("d")],
                ..Default::default()
            },
            TableRow {
                cells: vec![cell("1"), cell("2"), cell("3"), cell("4")],
                ..Default::default()
            },
        ],
        ..Default::default()
    };
    assert_both("15_complex_merge", &doc(vec![Block::Table(t)]));
}

#[test]
fn c16_body_image() {
    let d = doc(vec![
        para("Görselin üstündeki paragraf."),
        Block::Paragraph(Paragraph {
            props: ParaProps::default(),
            runs: vec![image_run(108.0, 112.0)],
        }),
        para("Görselin altındaki paragraf."),
    ]);
    assert_both("16_body_image", &d);
    // The PNG must not be re-encoded in either direction.
    let (back, _) = read_udf(&to_udf(&d));
    let Block::Paragraph(p) = &back.sections[0].blocks[1] else {
        panic!()
    };
    let Run::Image(i) = &p.runs[0] else {
        panic!("image lost")
    };
    assert_eq!(i.data.as_ref(), &png(), "PNG was re-encoded");
}

#[test]
fn c17_page_break() {
    // UDF cannot express a page break (EXP-012): the requirement is an explicit warning,
    // not a silent blank line.
    let d = doc(vec![
        para("Birinci sayfa."),
        Block::PageBreak,
        para("İkinci sayfa."),
    ]);
    let warns = assert_docx_roundtrip("17_page_break", &d);
    assert!(
        warns.contains(&WarningCode::PageBreakDropped),
        "a dropped page break must be reported"
    );
    // The text on both sides of the break must survive.
    let src = to_docx(&d);
    let mut w = WarningSink::new();
    let u = convert_bytes(&src, Direction::DocxToUdf, &mut w).unwrap();
    let (back, _) = read_udf(&u);
    let all: String = back.sections[0]
        .blocks
        .iter()
        .filter_map(|b| match b {
            Block::Paragraph(p) => Some(p.text()),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("|");
    assert!(all.contains("Birinci sayfa.") && all.contains("İkinci sayfa."));
}

#[test]
fn c18_header() {
    let mut d = doc(vec![para("Gövde metni.")]);
    d.sections[0].header = Some(HeaderFooter {
        blocks: vec![para("T.C. İSTANBUL ANADOLU 7. ASLİYE HUKUK MAHKEMESİ")],
        ..Default::default()
    });
    assert_both("18_header", &d);
}

#[test]
fn c19_footer() {
    let mut d = doc(vec![para("Gövde metni.")]);
    d.sections[0].footer = Some(HeaderFooter {
        blocks: vec![para("Av. Raci Çetin YÜKSEKBAŞ — 2026")],
        ..Default::default()
    });
    assert_both("19_footer", &d);
}

#[test]
fn c20_header_image() {
    let mut d = doc(vec![para("Antetli kağıt gövdesi.")]);
    d.sections[0].header = Some(HeaderFooter {
        blocks: vec![Block::Paragraph(Paragraph {
            props: ParaProps {
                alignment: Alignment::Center,
                ..Default::default()
            },
            runs: vec![image_run(108.0, 112.0)],
        })],
        stop_page: Some(1),
        ..Default::default()
    });
    assert_both("20_header_image", &d);
    let (back, _) = read_udf(&to_udf(&d));
    let h = back.sections[0].header.as_ref().expect("header lost");
    let Block::Paragraph(p) = &h.blocks[0] else {
        panic!()
    };
    assert!(
        matches!(p.runs.first(), Some(Run::Image(_))),
        "header image lost"
    );
}

#[test]
fn c21_landscape() {
    let mut d = doc(vec![para("Yatay sayfa.")]);
    d.sections[0].page.orientation = Orientation::Landscape;
    d.sections[0].page.width_pt = 841.89;
    d.sections[0].page.height_pt = 595.276;
    let warns = assert_docx_roundtrip("21_landscape", &d);
    assert!(
        warns.contains(&WarningCode::PageOrientationUnverified),
        "landscape must be flagged as unverified against UYAP"
    );
}

#[test]
fn c22_long_legal_document() {
    // A realistic pleading: headings, a numbered argument list, tabs, a table, a footer.
    let stops = vec![
        TabStop {
            pos_pt: 85.0,
            align: TabAlign::Left,
        },
        TabStop {
            pos_pt: 100.0,
            align: TabAlign::Left,
        },
    ];
    let mut blocks: Vec<Block> = vec![
        Block::Paragraph(Paragraph {
            props: ParaProps {
                alignment: Alignment::Center,
                ..Default::default()
            },
            runs: vec![run(
                "İSTANBUL ANADOLU 7. ASLİYE HUKUK MAHKEMESİ'NE",
                RunProps {
                    bold: true,
                    font_size_pt: Some(14.0),
                    ..Default::default()
                },
            )],
        }),
        Block::Paragraph(Paragraph {
            props: ParaProps {
                tab_stops: stops.clone(),
                ..Default::default()
            },
            runs: vec![run("DAVACI\t:\tAli VELİ", RunProps::default())],
        }),
        Block::Paragraph(Paragraph {
            props: ParaProps {
                tab_stops: stops.clone(),
                ..Default::default()
            },
            runs: vec![run("VEKİLİ\t:\tAv. Ayşe FATMA", RunProps::default())],
        }),
        Block::Paragraph(Paragraph {
            props: ParaProps {
                tab_stops: stops.clone(),
                ..Default::default()
            },
            runs: vec![run("KONU\t:\tAlacak davası", RunProps::default())],
        }),
        Block::Paragraph(Paragraph {
            props: ParaProps {
                alignment: Alignment::Left,
                ..Default::default()
            },
            runs: vec![run(
                "AÇIKLAMALAR",
                RunProps {
                    bold: true,
                    underline: true,
                    ..Default::default()
                },
            )],
        }),
    ];
    for i in 1..=120 {
        blocks.push(Block::Paragraph(Paragraph {
            props: ParaProps {
                alignment: Alignment::Justify,
                line_spacing_extra: 0.5,
                first_line_indent_pt: 21.0,
                list: Some(ListRef { list_id: 1, level: 1 }),
                ..Default::default()
            },
            runs: vec![
                run(&format!("{i}. "), RunProps { bold: true, ..Default::default() }),
                run(&format!("Müvekkil ile davalı arasındaki hukuki ilişki {i}. kez ele alınmıştır. {TR}"), RunProps::default()),
            ],
        }));
    }
    blocks.push(Block::Table(Table {
        column_widths: vec![60.0, 240.0, 120.0],
        border: TableBorder::Cell,
        rows: (0..12)
            .map(|i| TableRow {
                cells: vec![
                    cell(&format!("{}", i + 1)),
                    cell(&format!("Kalem {}", i + 1)),
                    cell("1.000,00 TL"),
                ],
                is_header: i == 0,
                ..Default::default()
            })
            .collect(),
        ..Default::default()
    }));
    let mut d = doc(blocks);
    d.lists = vec![ListDef {
        list_id: 1,
        kind: ListKind::Number(NumberKind::DecimalDot),
    }];
    d.sections[0].footer = Some(HeaderFooter {
        blocks: vec![para("Av. Ayşe FATMA")],
        ..Default::default()
    });
    assert_both("22_long_legal_document", &d);
}

#[test]
fn c23_output_name_collision() {
    use tavzih_core::convert::{convert_file_to, unique_output_path_in};
    let dir = std::env::temp_dir().join("tavzih-corpus-collision");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let out = dir.join("cikti");
    let src = dir.join("Dilekçe.docx");
    std::fs::write(&src, to_docx(&doc(vec![para("x")]))).unwrap();

    let mut produced = Vec::new();
    for _ in 0..3 {
        let r = convert_file_to(&src, &out);
        assert_eq!(r.status, Status::Success, "{:?}", r.error);
        assert!(r.source_unchanged);
        produced.push(PathBuf::from(r.output.unwrap()));
    }
    let names: Vec<String> = produced
        .iter()
        .map(|p| p.file_name().unwrap().to_string_lossy().to_string())
        .collect();
    assert_eq!(
        names,
        vec!["Dilekçe.udf", "Dilekçe (2).udf", "Dilekçe (3).udf"]
    );
    // Every one still exists: nothing was overwritten.
    for p in &produced {
        assert!(p.exists());
    }
    assert!(
        unique_output_path_in(&out, &src, "udf")
            .unwrap()
            .file_name()
            .unwrap()
            == "Dilekçe (4).udf"
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn c24_corrupt_docx() {
    use tavzih_core::ErrorCode;
    let mut w = WarningSink::new();
    // Not a ZIP at all.
    let e = docx::reader::read_docx(b"bu bir docx degil", &mut w).unwrap_err();
    assert_eq!(e.code, ErrorCode::InvalidDocx);
    // A ZIP that is not a WordprocessingML package.
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        use std::io::Write;
        let mut z = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        z.start_file("hello.txt", o).unwrap();
        z.write_all(b"hi").unwrap();
        z.finish().unwrap();
    }
    let bytes = cur.into_inner();
    dump("24_corrupt_docx", "docx", &bytes);
    let e = docx::reader::read_docx(&bytes, &mut w).unwrap_err();
    assert_eq!(e.code, ErrorCode::InvalidDocx);
    // Truncated ZIP.
    let good = to_docx(&doc(vec![para("x")]));
    let e = docx::reader::read_docx(&good[..good.len() / 2], &mut w).unwrap_err();
    assert_eq!(e.code, ErrorCode::InvalidDocx);
}

#[test]
fn c25_corrupt_udf() {
    use tavzih_core::ErrorCode;
    let mut w = WarningSink::new();
    let e = udf::reader::read_udf(b"bu bir udf degil", &mut w).unwrap_err();
    assert_eq!(e.code, ErrorCode::InvalidUdf);

    // A ZIP with no content.xml.
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        use std::io::Write;
        let mut z = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        z.start_file("sign.sgn", o).unwrap();
        z.write_all(b"only a signature").unwrap();
        z.finish().unwrap();
    }
    let bytes = cur.into_inner();
    dump("25_corrupt_udf", "udf", &bytes);
    assert_eq!(
        udf::reader::read_udf(&bytes, &mut w).unwrap_err().code,
        ErrorCode::InvalidUdf
    );

    // content.xml that is not well-formed enough to carry a buffer.
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        use std::io::Write;
        let mut z = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        z.start_file("content.xml", o).unwrap();
        z.write_all(b"<?xml version=\"1.0\"?><template format_id=\"1.8\"></template>")
            .unwrap();
        z.finish().unwrap();
    }
    assert_eq!(
        udf::reader::read_udf(&cur.into_inner(), &mut w)
            .unwrap_err()
            .code,
        ErrorCode::InvalidUdf
    );
}

// ------------------------------------------------- security corpus

#[test]
fn c26_hostile_archives_are_refused() {
    use tavzih_core::ErrorCode;
    let mut w = WarningSink::new();

    // XXE / entity expansion vector.
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        use std::io::Write;
        let mut z = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        z.start_file("content.xml", o).unwrap();
        z.write_all(
            b"<?xml version=\"1.0\"?><!DOCTYPE t [<!ENTITY a \"AAAA\">]><template format_id=\"1.8\">\
              <content><![CDATA[&a;]]></content><elements/></template>",
        )
        .unwrap();
        z.finish().unwrap();
    }
    let e = udf::reader::read_udf(&cur.into_inner(), &mut w).unwrap_err();
    assert_eq!(
        e.code,
        ErrorCode::UnsafeArchive,
        "a DOCTYPE must be refused"
    );

    // Zip Slip entry name.
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        use std::io::Write;
        let mut z = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        z.start_file("../../../../etc/passwd", o).unwrap();
        z.write_all(b"pwned").unwrap();
        z.start_file("content.xml", o).unwrap();
        z.write_all(b"<template/>").unwrap();
        z.finish().unwrap();
    }
    let e = udf::reader::read_udf(&cur.into_inner(), &mut w).unwrap_err();
    assert_eq!(
        e.code,
        ErrorCode::UnsafeArchive,
        "path traversal must be refused"
    );
}

#[test]
fn c27_empty_and_degenerate_documents() {
    // An empty document must still produce a valid, reopenable file in both formats.
    let d = doc(vec![]);
    let db = to_docx(&d);
    docx::writer::validate(&db).unwrap();
    let (r, _) = read_docx(&db);
    assert_eq!(r.sections.len(), 1);

    let d2 = doc(vec![para("")]);
    let ub = to_udf(&d2);
    let (r2, _) = read_udf(&ub);
    assert_eq!(r2.sections.len(), 1);
}

#[test]
fn c28_pathological_text_is_not_corrupted() {
    // Characters that could break CDATA, XML escaping, or the offset arithmetic.
    let d = doc(vec![
        para("meta: <tag> & \"quotes\" 'apos'"),
        para("CDATA sonu: ]]> devam ediyor"),
        para("astral: \u{1F600}\u{1F1F9}\u{1F1F7} bitti"),
        para("nbsp:\u{00A0}ve cedilla:\u{00B8}son"),
    ]);
    let ub = to_udf(&d);
    let (back, _) = read_udf(&ub);
    let got: Vec<String> = back.sections[0]
        .blocks
        .iter()
        .filter_map(|b| match b {
            Block::Paragraph(p) => Some(p.text()),
            _ => None,
        })
        .collect();
    assert_eq!(got[0], "meta: <tag> & \"quotes\" 'apos'");
    assert_eq!(got[1], "CDATA sonu: ]]> devam ediyor");
    assert_eq!(got[2], "astral: \u{1F600}\u{1F1F9}\u{1F1F7} bitti");
    assert_eq!(got[3], "nbsp:\u{00A0}ve cedilla:\u{00B8}son");

    let db = to_docx(&d);
    let (back2, _) = read_docx(&db);
    let got2: Vec<String> = back2.sections[0]
        .blocks
        .iter()
        .filter_map(|b| match b {
            Block::Paragraph(p) => Some(p.text()),
            _ => None,
        })
        .collect();
    assert_eq!(got2, got);
}

#[test]
fn c29_soft_line_breaks_are_reported_not_silently_flattened() {
    // UDF has no intra-paragraph line break (EXP-002). Turning one into a space is the
    // safe mapping, but it merges two visual lines, so the user must be told.
    let d = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps::default(),
        runs: vec![
            run("Birinci satır", RunProps::default()),
            Run::LineBreak {
                props: RunProps::default(),
            },
            run("ikinci satır", RunProps::default()),
        ],
    })]);
    let mut w = WarningSink::new();
    let xml = udf::writer::write_content_xml(&d, &mut w).unwrap();
    udf::writer::validate(&xml).unwrap();
    let codes: Vec<WarningCode> = w.into_vec().iter().map(|x| x.code).collect();
    assert!(
        codes.contains(&WarningCode::LineBreakConverted),
        "a soft line break must be reported, got {codes:?}"
    );
    // And no text may be lost in the process.
    let (back, _) = read_udf(&udf::writer::package(&xml).unwrap());
    let Block::Paragraph(p) = &back.sections[0].blocks[0] else {
        panic!()
    };
    assert_eq!(p.text(), "Birinci satır ikinci satır");
}

// ===================================================================== QA regressions
// Each of these encodes a defect found by manual QA on genuine legal documents.

/// Extract the twips value of an attribute from the first `<w:ind .../>` in a package part.
fn ind_attr(docx: &[u8], part: &str, attr: &str) -> Option<i64> {
    let s = part_text(docx, part);
    let i = s.find("<w:ind ")?;
    let tag = &s[i..i + s[i..].find("/>")?];
    let key = format!("{attr}=\"");
    let a = tag.find(&key)? + key.len();
    let b = tag[a..].find('"')? + a;
    tag[a..b].parse().ok()
}

fn part_text(docx: &[u8], part: &str) -> String {
    use std::io::Read;
    let mut z = zip::ZipArchive::new(std::io::Cursor::new(docx)).unwrap();
    let mut s = String::new();
    if let Ok(mut f) = z.by_name(part) {
        f.read_to_string(&mut s).unwrap();
    }
    s
}

fn part_names(docx: &[u8]) -> Vec<String> {
    let mut z = zip::ZipArchive::new(std::io::Cursor::new(docx)).unwrap();
    (0..z.len())
        .filter_map(|i| z.by_index(i).ok().map(|f| f.name().to_string()))
        .collect()
}

/// QA ISSUE 3 — legal labels were pushed off the left edge of the page.
///
/// UDF `Hanging` is the hanging-indent amount measured from `LeftIndent`. Emitting
/// `w:hanging` without `w:left` put the first line at a negative position.
#[test]
fn c30_hanging_indent_never_puts_the_first_line_off_page() {
    // The shape observed in genuine pleadings: LeftIndent=0, Hanging≈138.
    let d = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps {
            left_indent_pt: 137.857,
            hanging_pt: 137.857,
            tab_stops: vec![
                TabStop {
                    pos_pt: 26.0,
                    align: TabAlign::Left,
                },
                TabStop {
                    pos_pt: 139.0,
                    align: TabAlign::Left,
                },
            ],
            ..Default::default()
        },
        runs: vec![run("KONU\t\t\t:\tDava dilekçesidir.", RunProps::default())],
    })]);
    let bytes = to_docx(&d);
    let left = ind_attr(&bytes, "word/document.xml", "w:left").expect("w:left must be emitted");
    let hanging = ind_attr(&bytes, "word/document.xml", "w:hanging").expect("w:hanging");
    assert!(
        left - hanging >= 0,
        "first line would sit at {} twips, off the page (left={left}, hanging={hanging})",
        left - hanging
    );
    assert_eq!(left, 2757);
    assert_eq!(hanging, 2757);
}

/// The same geometry must survive a full UDF round trip without drifting.
#[test]
fn c31_legal_label_value_layout_round_trips() {
    for hanging in [137.857_f32, 27.857, 139.0, 27.381] {
        let d = doc(vec![Block::Paragraph(Paragraph {
            props: ParaProps {
                left_indent_pt: hanging,
                hanging_pt: hanging,
                alignment: Alignment::Justify,
                ..Default::default()
            },
            runs: vec![run("DAVALI\t:\tAli VELİ", RunProps::default())],
        })]);
        let (back, _) = read_udf(&to_udf(&d));
        let Block::Paragraph(p) = &back.sections[0].blocks[0] else {
            panic!()
        };
        assert!(
            (p.props.hanging_pt - hanging).abs() < 0.01,
            "hanging drifted: {} != {hanging}",
            p.props.hanging_pt
        );
        assert!(
            (p.props.left_indent_pt - hanging).abs() < 0.01,
            "left indent drifted: {} != {hanging}",
            p.props.left_indent_pt
        );
        // And the emitted UDF must carry LeftIndent=0, which is what UYAP writes.
        let xml =
            String::from_utf8(udf::writer::write_content_xml(&d, &mut WarningSink::new()).unwrap())
                .unwrap();
        assert!(
            !xml.contains("LeftIndent="),
            "LeftIndent should decompose to 0 and be omitted, got: {}",
            &xml[xml.find("<paragraph").unwrap()..][..160]
        );
    }
}

/// QA ISSUE 2 — Word showed "Resim görüntülenemiyor" for letterhead images.
///
/// OOXML relationships are part-scoped. A header image's relationship must live in
/// `word/_rels/header1.xml.rels`, not in the document part's.
#[test]
fn c32_header_image_relationship_is_scoped_to_the_header_part() {
    let mut d = doc(vec![para("Gövde")]);
    d.sections[0].header = Some(HeaderFooter {
        blocks: vec![Block::Paragraph(Paragraph {
            props: ParaProps::default(),
            runs: vec![image_run(108.0, 112.0)],
        })],
        ..Default::default()
    });
    let bytes = to_docx(&d); // to_docx() validates, which now enforces scoping
    let names = part_names(&bytes);
    assert!(
        names.iter().any(|n| n == "word/_rels/header1.xml.rels"),
        "header rels part missing"
    );

    let hdr = part_text(&bytes, "word/header1.xml");
    let rid = {
        let i = hdr.find("r:embed=\"").expect("header must embed an image") + 9;
        hdr[i..i + hdr[i..].find('"').unwrap()].to_string()
    };
    let hdr_rels = part_text(&bytes, "word/_rels/header1.xml.rels");
    assert!(
        hdr_rels.contains(&format!("Id=\"{rid}\"")),
        "header references {rid} but its own rels does not define it"
    );
    // The document part must NOT be the one carrying the header's image relationship.
    let doc_rels = part_text(&bytes, "word/_rels/document.xml.rels");
    assert!(
        !doc_rels.contains("media/image"),
        "header image relationship leaked into the document scope"
    );
    // The bytes must actually exist at the referenced target.
    assert!(names.iter().any(|n| n.starts_with("word/media/image")));

    // And the image must still survive being read back.
    let (back, _) = read_docx(&bytes);
    let h = back.sections[0].header.as_ref().expect("header lost");
    let n: usize = h
        .blocks
        .iter()
        .map(|b| match b {
            Block::Paragraph(p) => p.runs.iter().filter(|r| matches!(r, Run::Image(_))).count(),
            _ => 0,
        })
        .sum();
    assert_eq!(n, 1, "header image lost on read-back");
}

/// A dangling reference must be caught by validation, not shipped to Word.
#[test]
fn c33_validator_rejects_a_header_reference_it_cannot_resolve() {
    let mut d = doc(vec![para("x")]);
    d.sections[0].header = Some(HeaderFooter {
        blocks: vec![Block::Paragraph(Paragraph {
            props: ParaProps::default(),
            runs: vec![image_run(50.0, 50.0)],
        })],
        ..Default::default()
    });
    let bytes = to_docx(&d);
    // Rebuild without the header's rels part.
    let mut z = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        use std::io::{Read, Write};
        let mut zw = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        for i in 0..z.len() {
            let mut f = z.by_index(i).unwrap();
            let n = f.name().to_string();
            if n == "word/_rels/header1.xml.rels" {
                continue;
            }
            let mut v = Vec::new();
            f.read_to_end(&mut v).unwrap();
            zw.start_file(n, o).unwrap();
            zw.write_all(&v).unwrap();
        }
        zw.finish().unwrap();
    }
    let e = docx::writer::validate(&cur.into_inner()).unwrap_err();
    assert_eq!(e.code, tavzih_core::ErrorCode::OutputValidationFailed);
}

/// QA ISSUE 1 — the page-number field was dropped instead of rebuilt.
#[test]
fn c34_page_number_becomes_a_real_updatable_word_field() {
    let mut d = doc(vec![para("Gövde")]);
    d.sections[0].footer = Some(HeaderFooter {
        blocks: vec![para("Av. Ayşe FATMA")],
        page_number: Some(PageNumberField {
            prefix: Some("Sayfa ".into()),
            separator: Some("/".into()),
            font_family: Some("Arial".into()),
            font_size_pt: Some(11.0),
            raw_spec: Some("BSP32_2120".into()),
            ..Default::default()
        }),
        ..Default::default()
    });
    let bytes = to_docx(&d);
    let ftr = part_text(&bytes, "word/footer1.xml");
    assert!(ftr.contains("PAGE"), "no PAGE field instruction emitted");
    assert!(
        ftr.contains("NUMPAGES"),
        "separator implies a total, so NUMPAGES is required"
    );
    assert!(
        ftr.contains("fldCharType=\"begin\""),
        "not a real complex field"
    );
    assert!(ftr.contains("fldCharType=\"end\""));
    assert!(ftr.contains("Sayfa "), "prefix text lost");
    assert!(ftr.contains("Av. Ayşe FATMA"), "existing footer text lost");
    // The existing footer text must not be replaced by the field.
    let mut w = WarningSink::new();
    let _ = docx::writer::write_docx(&d, &mut w).unwrap();
    let codes: Vec<WarningCode> = w.into_vec().iter().map(|x| x.code).collect();
    assert!(codes.contains(&WarningCode::PageNumberFieldApproximated));
    assert!(!codes.contains(&WarningCode::PageNumberFieldDropped));
}

/// A page-number-only field, with no separator, must emit PAGE and not NUMPAGES.
#[test]
fn c35_page_number_without_a_total_emits_only_page() {
    let mut d = doc(vec![para("x")]);
    d.sections[0].footer = Some(HeaderFooter {
        page_number: Some(PageNumberField {
            raw_spec: Some("BSP32_72".into()),
            font_family: Some("Arial".into()),
            ..Default::default()
        }),
        ..Default::default()
    });
    let ftr = part_text(&to_docx(&d), "word/footer1.xml");
    assert!(ftr.contains("PAGE"));
    assert!(!ftr.contains("NUMPAGES"));
}

/// QA ISSUE 5 — "Sayfa boyutu A4'e çevrildi — 612x792 pt". 612x792 is US Letter.
#[test]
fn c36_us_letter_is_never_called_a4_and_the_change_is_a_real_loss() {
    let mut d = doc(vec![para("x")]);
    d.sections[0].page = PageSetup {
        width_pt: 612.0,
        height_pt: 792.0,
        ..PageSetup::a4_uyap()
    };
    let mut w = WarningSink::new();
    let xml = udf::writer::write_content_xml(&d, &mut w).unwrap();
    udf::writer::validate(&xml).unwrap();
    let ws = w.into_vec();
    let pw = ws
        .iter()
        .find(|x| x.code == WarningCode::PageSizeChanged)
        .expect("a page-size change must be reported");
    let detail = pw.detail.clone().unwrap_or_default();
    assert!(
        detail.contains("US Letter"),
        "source size must be named: {detail}"
    );
    assert!(
        detail.contains("612x792"),
        "source dimensions must be stated: {detail}"
    );
    assert!(detail.contains("A4"), "target size must be named: {detail}");
    assert!(
        detail.contains("595x842"),
        "A4's real dimensions must be stated: {detail}"
    );
    assert_eq!(
        pw.severity,
        Severity::Loss,
        "changing page geometry is a real loss"
    );
    // An A4 source must not warn at all.
    let mut w2 = WarningSink::new();
    let _ = udf::writer::write_content_xml(&doc(vec![para("x")]), &mut w2).unwrap();
    assert!(!w2.has(WarningCode::PageSizeChanged));
}

/// QA ISSUE 6 — a genuine court decision lost its form labels, leaving bare colons.
///
/// `<field>` is a self-closing leaf carrying (startOffset, length) into the content buffer,
/// exactly like `<content>`. Treating it as metadata dropped every label and value.
#[test]
fn c37_udf_form_field_text_is_preserved_as_static_content() {
    // Build a UDF by hand in the shape UYAP produces for a form document.
    let content = "İLİ	: İSTANBUL
KARAR NO	: 2026/428
";
    let xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<template format_id=\"1.8\" >\n         <content><![CDATA[{content}]]></content>\n         <properties><pageFormat mediaSizeName=\"1\" leftMargin=\"70.875\" rightMargin=\"70.875\"          topMargin=\"70.875\" bottomMargin=\"70.875\" paperOrientation=\"1\" headerFOffset=\"20.0\"          footerFOffset=\"20.0\" /></properties>\n<elements resolver=\"hvl-default\" >         <paragraph Alignment=\"0\">         <field fieldType=\"2\" isList=\"false\" fieldName=\"ili\" bold=\"true\" startOffset=\"0\" length=\"3\" />         <tab startOffset=\"3\" length=\"1\" />         <content startOffset=\"4\" length=\"2\" />         <field fieldType=\"1\" isList=\"false\" fieldName=\"ilAdi\" startOffset=\"6\" length=\"8\" />         <content startOffset=\"14\" length=\"1\" />         </paragraph>         <paragraph Alignment=\"0\">         <field fieldType=\"2\" isList=\"false\" fieldName=\"kararNoLbl\" bold=\"true\" startOffset=\"15\" length=\"8\" />         <tab startOffset=\"23\" length=\"1\" />         <content startOffset=\"24\" length=\"2\" />         <field fieldType=\"1\" isList=\"false\" fieldName=\"kararNo\" startOffset=\"26\" length=\"9\" />         <content startOffset=\"35\" length=\"1\" />         </paragraph></elements>\n         <styles><style name=\"hvl-default\" family=\"Times New Roman\" size=\"12\" description=\"Gövde\" /></styles>\n         </template>"
    );
    let udf_bytes = udf::writer::package(xml.as_bytes()).unwrap();
    let (parsed, warns) = read_udf(&udf_bytes);

    let text: Vec<String> = parsed.sections[0]
        .blocks
        .iter()
        .filter_map(|b| match b {
            Block::Paragraph(p) => Some(p.text()),
            _ => None,
        })
        .collect();
    // Labels AND values must both survive, in order, not just the colons.
    assert_eq!(
        text[0], "İLİ\t: İSTANBUL",
        "form label or value lost: {:?}",
        text
    );
    assert_eq!(
        text[1], "KARAR NO\t: 2026/428",
        "form label or value lost: {:?}",
        text
    );

    // Staticizing is expected, not a fidelity loss.
    assert!(warns.contains(&WarningCode::FormFieldsStaticized));
    assert!(!warns.contains(&WarningCode::FormContentLost));
    assert_eq!(WarningCode::FormFieldsStaticized.severity(), Severity::Info);

    // The formatting carried on the field must survive too.
    let Block::Paragraph(p0) = &parsed.sections[0].blocks[0] else {
        panic!()
    };
    assert!(
        p0.runs[0].props().unwrap().bold,
        "field run formatting lost"
    );

    // And the whole thing must reach a readable DOCX.
    let bytes = to_docx(&parsed);
    let body = part_text(&bytes, "word/document.xml");
    assert!(body.contains("İLİ"), "label missing from DOCX");
    assert!(body.contains("İSTANBUL"), "value missing from DOCX");
    assert!(body.contains("2026/428"), "value missing from DOCX");
}

/// An unresolvable field span is a genuine loss and must say so.
#[test]
fn c38_unresolvable_form_field_reports_content_loss() {
    let xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<template format_id=\"1.8\" >\n         <content><![CDATA[abc\n]]></content>\n         <properties><pageFormat mediaSizeName=\"1\" leftMargin=\"70.875\" rightMargin=\"70.875\"          topMargin=\"70.875\" bottomMargin=\"70.875\" paperOrientation=\"1\" headerFOffset=\"20.0\"          footerFOffset=\"20.0\" /></properties>\n<elements resolver=\"hvl-default\" >         <paragraph Alignment=\"0\"><content startOffset=\"0\" length=\"4\" />         <field fieldName=\"ghost\" startOffset=\"9999\" length=\"5\" /></paragraph></elements>\n         <styles><style name=\"hvl-default\" family=\"Times New Roman\" size=\"12\" /></styles>\n</template>";
    let (_, warns) = read_udf(&udf::writer::package(xml.as_bytes()).unwrap());
    assert!(
        warns.contains(&WarningCode::FormContentLost),
        "silent loss: {warns:?}"
    );
    assert_eq!(WarningCode::FormContentLost.severity(), Severity::Loss);
}

/// QA ISSUE 8 — check that list numbering is not duplicated.
#[test]
fn c39_list_numbering_is_not_duplicated() {
    // A paragraph that is a list member must not also carry a literal marker in its text.
    let mut d = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps {
            list: Some(ListRef {
                list_id: 1,
                level: 1,
            }),
            ..Default::default()
        },
        runs: vec![run("Birinci madde", RunProps::default())],
    })]);
    d.lists = vec![ListDef {
        list_id: 1,
        kind: ListKind::Number(NumberKind::DecimalDot),
    }];
    let (back, _) = read_udf(&to_udf(&d));
    let Block::Paragraph(p) = &back.sections[0].blocks[0] else {
        panic!()
    };
    assert_eq!(
        p.text(),
        "Birinci madde",
        "a list marker leaked into the text"
    );
    assert!(p.props.list.is_some(), "list membership lost");

    // Round-tripping must not accumulate a marker either.
    let bytes = to_docx(&back);
    let body = part_text(&bytes, "word/document.xml");
    assert!(
        !body.contains("1. Birinci madde"),
        "numbering duplicated into the run text"
    );
    assert!(
        body.contains("<w:numPr>"),
        "numbering should come from numPr, not literal text"
    );
}

// ===================================================================== batch conversion

fn batch_dir(tag: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!("tavzih-batch-{tag}"));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

fn write_docx_file(dir: &Path, name: &str) -> PathBuf {
    let p = dir.join(name);
    std::fs::write(&p, to_docx(&doc(vec![para("Word kaynak"), para(TR)]))).unwrap();
    p
}

fn write_udf_file(dir: &Path, name: &str) -> PathBuf {
    let p = dir.join(name);
    std::fs::write(&p, to_udf(&doc(vec![para("UDF kaynak"), para(TR)]))).unwrap();
    p
}

fn zip_entries(path: &Path) -> Vec<String> {
    let bytes = std::fs::read(path).unwrap();
    let mut z = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
    (0..z.len())
        .map(|i| z.by_index(i).unwrap().name().to_string())
        .collect()
}

/// Every batch member's source must be byte-identical afterwards.
fn assert_sources_untouched(paths: &[PathBuf], before: &[String]) {
    for (p, b) in paths.iter().zip(before) {
        assert_eq!(
            &tavzih_core::convert::sha256_file(p).unwrap(),
            b,
            "RELEASE BLOCKER: source {} changed",
            p.display()
        );
    }
}

#[test]
fn c40_single_file_batch_produces_a_plain_document_not_a_zip() {
    let d = batch_dir("single");
    let out = d.join("cikti");
    let src = write_docx_file(&d, "Tek.docx");
    let before = vec![tavzih_core::convert::sha256_file(&src).unwrap()];

    let r = tavzih_core::convert::convert_batch_to(
        std::slice::from_ref(&src),
        &out,
        Some("2026-08-30_2005"),
    );
    assert_eq!(r.total, 1);
    assert_eq!(r.failed, 0);
    assert!(!r.is_zip, "a single file must not be zipped");
    assert!(r.all_sources_unchanged);
    let o = PathBuf::from(r.output.unwrap());
    assert_eq!(o.extension().unwrap(), "udf");
    assert!(o.exists());
    assert_sources_untouched(&[src], &before);
    let _ = std::fs::remove_dir_all(&d);
}

#[test]
fn c41_homogeneous_batch_zips_into_one_target_folder() {
    let d = batch_dir("homogeneous");
    let out = d.join("cikti");
    let srcs: Vec<PathBuf> = (1..=4)
        .map(|i| write_docx_file(&d, &format!("Belge{i}.docx")))
        .collect();
    let before: Vec<String> = srcs
        .iter()
        .map(|p| tavzih_core::convert::sha256_file(p).unwrap())
        .collect();

    let r = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2005"));
    assert_eq!(r.total, 4);
    assert_eq!(
        r.succeeded + r.warned,
        4,
        "{:?}",
        r.items.iter().map(|i| &i.error).collect::<Vec<_>>()
    );
    assert_eq!(r.failed, 0);
    assert!(r.is_zip);
    assert!(r.all_sources_unchanged);

    let zip = PathBuf::from(r.output.unwrap());
    assert_eq!(zip.extension().unwrap(), "zip");
    assert!(zip
        .file_name()
        .unwrap()
        .to_string_lossy()
        .starts_with("Tavzih_Dönüşüm_2026-08-30_2005"));
    let entries = zip_entries(&zip);
    assert_eq!(entries.len(), 4);
    assert!(entries.iter().all(|e| e.starts_with("UDF/")), "{entries:?}");
    // Outputs only — never the user's sources.
    assert!(
        !entries.iter().any(|e| e.ends_with(".docx")),
        "source documents leaked into the ZIP"
    );
    assert_sources_untouched(&srcs, &before);
    let _ = std::fs::remove_dir_all(&d);
}

#[test]
fn c42_mixed_batch_routes_each_file_by_its_own_direction() {
    let d = batch_dir("mixed");
    let out = d.join("cikti");
    let mut srcs: Vec<PathBuf> = (1..=3)
        .map(|i| write_docx_file(&d, &format!("W{i}.docx")))
        .collect();
    srcs.extend((1..=2).map(|i| write_udf_file(&d, &format!("U{i}.udf"))));
    let before: Vec<String> = srcs
        .iter()
        .map(|p| tavzih_core::convert::sha256_file(p).unwrap())
        .collect();

    let r = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2005"));
    assert_eq!(r.total, 5);
    assert_eq!(r.failed, 0);
    assert!(r.is_zip);

    let entries = zip_entries(&PathBuf::from(r.output.unwrap()));
    let udf: Vec<_> = entries.iter().filter(|e| e.starts_with("UDF/")).collect();
    let docx: Vec<_> = entries.iter().filter(|e| e.starts_with("DOCX/")).collect();
    assert_eq!(
        udf.len(),
        3,
        "3 DOCX sources should yield 3 UDF outputs: {entries:?}"
    );
    assert_eq!(
        docx.len(),
        2,
        "2 UDF sources should yield 2 DOCX outputs: {entries:?}"
    );
    assert_sources_untouched(&srcs, &before);
    let _ = std::fs::remove_dir_all(&d);
}

#[test]
fn c43_a_failing_file_does_not_abort_the_rest_of_the_batch() {
    let d = batch_dir("partial");
    let out = d.join("cikti");
    let good1 = write_docx_file(&d, "Iyi1.docx");
    let bad = d.join("Bozuk.docx");
    std::fs::write(&bad, b"PK\x03\x04 not a real docx").unwrap();
    let good2 = write_udf_file(&d, "Iyi2.udf");
    let unsupported = d.join("Rapor.pdf");
    std::fs::write(&unsupported, b"%PDF-1.7").unwrap();
    let srcs = vec![
        good1.clone(),
        bad.clone(),
        good2.clone(),
        unsupported.clone(),
    ];
    let before: Vec<String> = srcs
        .iter()
        .map(|p| tavzih_core::convert::sha256_file(p).unwrap())
        .collect();

    let r = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2005"));
    assert_eq!(r.total, 4);
    assert_eq!(r.failed, 2, "two files should fail");
    assert_eq!(r.succeeded + r.warned, 2, "two files should still convert");
    assert_eq!(
        r.status,
        Status::Warning,
        "a partial batch is not a total failure"
    );

    // The successful outputs are still delivered.
    assert!(r.is_zip);
    let entries = zip_entries(&PathBuf::from(r.output.clone().unwrap()));
    assert_eq!(entries.len(), 2, "{entries:?}");

    // Per-file reasons are available for the UI.
    let codes: Vec<Option<String>> = r
        .items
        .iter()
        .map(|i| i.error.as_ref().map(|e| e.code.clone()))
        .collect();
    assert_eq!(codes[1].as_deref(), Some("INVALID_DOCX"));
    assert_eq!(codes[3].as_deref(), Some("INVALID_EXTENSION"));
    assert!(r.all_sources_unchanged);
    assert_sources_untouched(&srcs, &before);
    let _ = std::fs::remove_dir_all(&d);
}

#[test]
fn c44_a_batch_where_everything_fails_reports_failure_and_no_zip() {
    let d = batch_dir("allfail");
    let out = d.join("cikti");
    let a = d.join("a.docx");
    let b = d.join("b.udf");
    std::fs::write(&a, b"nope").unwrap();
    std::fs::write(&b, b"nope").unwrap();
    let r = tavzih_core::convert::convert_batch_to(&[a, b], &out, Some("2026-08-30_2005"));
    assert_eq!(r.status, Status::Failure);
    assert_eq!(r.failed, 2);
    assert!(
        r.output.is_none(),
        "nothing converted, so there is nothing to package"
    );
    let _ = std::fs::remove_dir_all(&d);
}

#[test]
fn c45_identical_file_names_from_different_folders_both_survive_the_zip() {
    let d = batch_dir("dupnames");
    let out = d.join("cikti");
    let f1 = d.join("klasor1");
    let f2 = d.join("klasor2");
    std::fs::create_dir_all(&f1).unwrap();
    std::fs::create_dir_all(&f2).unwrap();
    let a = write_docx_file(&f1, "Dilekçe.docx");
    let b = write_docx_file(&f2, "Dilekçe.docx");

    let r = tavzih_core::convert::convert_batch_to(&[a, b], &out, Some("2026-08-30_2005"));
    assert_eq!(r.failed, 0);
    let entries = zip_entries(&PathBuf::from(r.output.unwrap()));
    assert_eq!(
        entries.len(),
        2,
        "one of the two documents was lost: {entries:?}"
    );
    assert!(
        entries.contains(&"UDF/Dilekçe.udf".to_string()),
        "{entries:?}"
    );
    assert!(
        entries.iter().any(|e| e.contains("(2)")),
        "the colliding name must be disambiguated: {entries:?}"
    );
    let _ = std::fs::remove_dir_all(&d);
}

#[test]
fn c46_a_second_batch_at_the_same_timestamp_does_not_overwrite_the_first() {
    let d = batch_dir("zipcollide");
    let out = d.join("cikti");
    let srcs = vec![write_docx_file(&d, "A.docx"), write_docx_file(&d, "B.docx")];
    let r1 = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2005"));
    let r2 = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2005"));
    let p1 = PathBuf::from(r1.output.unwrap());
    let p2 = PathBuf::from(r2.output.unwrap());
    assert_ne!(p1, p2, "the second batch overwrote the first");
    assert!(p1.exists() && p2.exists());
    assert!(p2.file_name().unwrap().to_string_lossy().contains("(2)"));
    let _ = std::fs::remove_dir_all(&d);
}

#[test]
fn c47_batch_outputs_are_not_left_loose_beside_the_zip() {
    let d = batch_dir("noloose");
    let out = d.join("cikti");
    let srcs = vec![write_docx_file(&d, "A.docx"), write_docx_file(&d, "B.docx")];
    let r = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2005"));
    assert!(r.is_zip);
    let loose: Vec<String> = std::fs::read_dir(&out)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter(|n| !n.ends_with(".zip"))
        .collect();
    assert!(
        loose.is_empty(),
        "loose duplicates left next to the ZIP: {loose:?}"
    );
    let _ = std::fs::remove_dir_all(&d);
}

/// QA policy: an intentionally omitted electronic signature is not damage.
#[test]
fn c48_signature_omission_alone_keeps_the_result_green() {
    use std::io::Write;
    let d = doc(vec![para("Karar metni")]);
    let xml = udf::writer::write_content_xml(&d, &mut WarningSink::new()).unwrap();
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        let mut z = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        z.start_file("content.xml", o).unwrap();
        z.write_all(&xml).unwrap();
        z.start_file("sign.sgn", o).unwrap();
        z.write_all(b"signature-bytes").unwrap();
        z.finish().unwrap();
    }
    let signed = cur.into_inner();

    let dir = std::env::temp_dir().join("tavzih-sig-severity");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let src = dir.join("Karar.udf");
    std::fs::write(&src, &signed).unwrap();

    let r = tavzih_core::convert::convert_file_to(&src, &dir.join("cikti"));
    assert_eq!(
        r.status,
        Status::Success,
        "an omitted signature must not make the conversion amber: {:?}",
        r.warnings
    );
    // It is still reported, just as information.
    let sig = r
        .warnings
        .iter()
        .find(|w| w.code == WarningCode::SignatureDropped)
        .expect("the omission must still be stated");
    assert_eq!(sig.severity, Severity::Info);
    assert!(!sig.data_loss);
    let _ = std::fs::remove_dir_all(&dir);
}

/// A genuine loss must still turn the result amber.
#[test]
fn c49_a_real_loss_still_downgrades_the_result() {
    let dir = std::env::temp_dir().join("tavzih-loss-severity");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let mut d = doc(vec![para("a"), Block::PageBreak, para("b")]);
    d.sections[0].page = PageSetup {
        width_pt: 612.0,
        height_pt: 792.0,
        ..PageSetup::a4_uyap()
    };
    let src = dir.join("Letter.docx");
    std::fs::write(&src, to_docx(&d)).unwrap();

    let r = tavzih_core::convert::convert_file_to(&src, &dir.join("cikti"));
    assert_eq!(r.status, Status::Warning, "{:?}", r.warnings);
    assert!(r.warnings.iter().any(|w| w.severity == Severity::Loss));
    let _ = std::fs::remove_dir_all(&dir);
}

/// A UDF built in the exact shape that failed manual QA, staged for the UYAP gate.
#[test]
fn c50_qa_layout_case_for_manual_acceptance() {
    let stops = vec![
        TabStop {
            pos_pt: 26.0,
            align: TabAlign::Left,
        },
        TabStop {
            pos_pt: 54.0,
            align: TabAlign::Left,
        },
        TabStop {
            pos_pt: 83.0,
            align: TabAlign::Left,
        },
        TabStop {
            pos_pt: 111.0,
            align: TabAlign::Left,
        },
        TabStop {
            pos_pt: 139.0,
            align: TabAlign::Left,
        },
    ];
    let label = |text: &str, hanging: f32| {
        Block::Paragraph(Paragraph {
            props: ParaProps {
                alignment: Alignment::Justify,
                line_spacing_extra: 0.5,
                left_indent_pt: hanging,
                hanging_pt: hanging,
                tab_stops: stops.clone(),
                ..Default::default()
            },
            runs: vec![run(text, RunProps::default())],
        })
    };
    let mut d = doc(vec![
        Block::Paragraph(Paragraph {
            props: ParaProps { alignment: Alignment::Center, ..Default::default() },
            runs: vec![run("KIRKLARELİ İDARE MAHKEMESİ'NE", RunProps { bold: true, ..Default::default() })],
        }),
        label("Dosya No.\t\t\t:\t2026/428-E.", 139.0),
        label("DAVACI\t\t\t:\tAli VELİ", 139.0),
        label("VEKİLİ\t\t\t:\tAv. Ayşe FATMA", 139.0),
        label("DAVALI\t\t\t:\tKırklareli Üniversitesi Rektörlüğü", 139.0),
        label("İPTALİ İSTENEN İŞLEM\t:\tİdari işlemin iptali istemi", 139.0),
        label("TEBLİĞ TARİHİ\t\t:\t01.08.2026", 127.143),
        label("KONU\t\t\t:\tKırklareli İdare Mahkemesi'nin kararına karşı istinaf başvurumuzun sunulmasıdır. Bu satır sarkarak ikinci satıra geçmeli ve değerin altına hizalanmalıdır.", 137.857),
        label("SONUÇ VE İSTEM\t\t:\tYukarıda açıklanan nedenlerle kararın kaldırılmasını talep ederiz.", 27.857),
    ]);
    d.sections[0].header = Some(HeaderFooter {
        blocks: vec![Block::Paragraph(Paragraph {
            props: ParaProps {
                alignment: Alignment::Center,
                ..Default::default()
            },
            runs: vec![image_run(108.0, 112.0)],
        })],
        ..Default::default()
    });
    d.sections[0].footer = Some(HeaderFooter {
        blocks: vec![para("Av. Ayşe FATMA")],
        page_number: Some(PageNumberField {
            separator: Some("/".into()),
            font_family: Some("Arial".into()),
            font_size_pt: Some(11.0),
            raw_spec: Some("BSP32_2120".into()),
            ..Default::default()
        }),
        ..Default::default()
    });
    assert_both("26_qa_label_layout", &d);
}

/// P1 REGRESSION — Word refused a converted pleading with "Text Recovery".
///
/// UYAP writes the editor's full default ruler: real documents carry 455 tab stops running
/// out to 223 inches, of which only a dozen fall inside the page. Passing them through
/// produced 16,217 `<w:tab>` elements with positions to 321,732 twips, and Word rejected the
/// whole document. Well-formed XML with resolvable relationships is not the same thing as a
/// file Word will open.
#[test]
fn c51_absurd_tab_stops_are_bounded_to_what_word_accepts() {
    // The shape observed in the failing document.
    let stops: Vec<TabStop> = (1..=455)
        .map(|i| TabStop {
            pos_pt: i as f32 * 35.43307,
            align: TabAlign::Left,
        })
        .collect();
    let d = doc((0..90)
        .map(|i| {
            Block::Paragraph(Paragraph {
                props: ParaProps {
                    tab_stops: stops.clone(),
                    ..Default::default()
                },
                runs: vec![run(&format!("Paragraf {i}\tdeğer"), RunProps::default())],
            })
        })
        .collect());

    // to_docx() validates, and validation now enforces Word's limits.
    let bytes = to_docx(&d);
    let body = part_text(&bytes, "word/document.xml");

    let per_para: Vec<usize> = body
        .split("<w:tabs>")
        .skip(1)
        .map(|b| {
            b[..b.find("</w:tabs>").unwrap_or(b.len())]
                .matches("<w:tab ")
                .count()
        })
        .collect();
    assert!(
        per_para.iter().all(|n| *n <= 64),
        "a paragraph kept {} tab stops; Word accepts at most 64",
        per_para.iter().max().unwrap()
    );

    let positions: Vec<i64> = body
        .match_indices("w:pos=\"")
        .filter_map(|(i, _)| {
            let a = &body[i + 7..];
            a[..a.find('"')?].parse().ok()
        })
        .collect();
    assert!(!positions.is_empty(), "all tab stops were dropped");
    assert!(
        positions.iter().all(|p| *p <= 31_680),
        "a tab position of {} twips is outside Word's range",
        positions.iter().max().unwrap()
    );
    // Only stops inside the text column survive, so the part stays a sane size.
    assert!(
        body.len() < 200_000,
        "document.xml is {} bytes; the ruler was not bounded",
        body.len()
    );
}

/// Stops that the reader could actually have reached are a real loss and must be reported;
/// unreachable ones are not.
#[test]
fn c52_only_losing_reachable_tab_stops_is_reported() {
    // 500 stops packed inside the text column: more than Word accepts, so some real ones go.
    let packed: Vec<TabStop> = (1..=500)
        .map(|i| TabStop {
            pos_pt: i as f32 * 0.8,
            align: TabAlign::Left,
        })
        .collect();
    let mut w = WarningSink::new();
    let d = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps {
            tab_stops: packed,
            ..Default::default()
        },
        runs: vec![run("x", RunProps::default())],
    })]);
    docx::writer::write_docx(&d, &mut w).unwrap();
    assert!(
        w.has(WarningCode::TabStopsTrimmed),
        "dropping reachable tab stops must be reported"
    );

    // The unreachable ruler, by contrast, costs the reader nothing and must stay quiet.
    let ruler: Vec<TabStop> = (1..=455)
        .map(|i| TabStop {
            pos_pt: i as f32 * 35.43307,
            align: TabAlign::Left,
        })
        .collect();
    let mut w2 = WarningSink::new();
    let d2 = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps {
            tab_stops: ruler,
            ..Default::default()
        },
        runs: vec![run("x", RunProps::default())],
    })]);
    docx::writer::write_docx(&d2, &mut w2).unwrap();
    assert!(
        !w2.has(WarningCode::TabStopsTrimmed),
        "stops beyond the page are unreachable; dropping them is not a fidelity loss"
    );
}

/// The validator must refuse a package Word would reject, so this can never again be
/// reported as a successful conversion.
#[test]
fn c53_validator_refuses_a_package_that_exceeds_word_limits() {
    let good = to_docx(&doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps {
            tab_stops: vec![TabStop {
                pos_pt: 100.0,
                align: TabAlign::Left,
            }],
            ..Default::default()
        },
        runs: vec![run("x", RunProps::default())],
    })]));

    // Re-inject the failure shape: an out-of-range tab position.
    let broken = rewrite_part(&good, "word/document.xml", |xml| {
        xml.replace("w:pos=\"2000\"", "w:pos=\"321732\"")
    });
    let e = docx::writer::validate(&broken).unwrap_err();
    assert_eq!(e.code, tavzih_core::ErrorCode::OutputValidationFailed);
    assert!(e.detail.contains("321732"), "{}", e.detail);

    // And too many stops in one paragraph.
    let many = (0..80)
        .map(|i| format!("<w:tab w:val=\"left\" w:pos=\"{}\"/>", 100 + i * 10))
        .collect::<String>();
    let broken2 = rewrite_part(&good, "word/document.xml", |xml| {
        let i = xml.find("<w:tabs>").unwrap() + "<w:tabs>".len();
        let j = xml.find("</w:tabs>").unwrap();
        format!("{}{many}{}", &xml[..i], &xml[j..])
    });
    let e2 = docx::writer::validate(&broken2).unwrap_err();
    assert_eq!(e2.code, tavzih_core::ErrorCode::OutputValidationFailed);
    assert!(e2.detail.contains("tab stops"), "{}", e2.detail);
}

/// Paragraph properties must be emitted in CT_PPr schema order.
#[test]
fn c54_paragraph_properties_are_in_schema_order() {
    let d = doc(vec![Block::Paragraph(Paragraph {
        props: ParaProps {
            alignment: Alignment::Justify,
            left_indent_pt: 36.0,
            hanging_pt: 18.0,
            space_before_pt: 6.0,
            line_spacing_extra: 0.5,
            tab_stops: vec![TabStop {
                pos_pt: 100.0,
                align: TabAlign::Left,
            }],
            list: Some(ListRef {
                list_id: 1,
                level: 1,
            }),
            ..Default::default()
        },
        runs: vec![run("x", RunProps::default())],
    })]);
    let mut dd = d.clone();
    dd.lists = vec![ListDef {
        list_id: 1,
        kind: ListKind::Number(NumberKind::DecimalDot),
    }];
    let body = part_text(&to_docx(&dd), "word/document.xml");
    let ppr = &body[body.find("<w:pPr>").unwrap()..body.find("</w:pPr>").unwrap()];
    const ORDER: [&str; 5] = ["<w:numPr>", "<w:tabs>", "<w:spacing", "<w:ind", "<w:jc"];
    let mut last = 0usize;
    for tag in ORDER {
        let at = ppr
            .find(tag)
            .unwrap_or_else(|| panic!("{tag} missing from {ppr}"));
        assert!(at >= last, "{tag} is out of CT_PPr order in {ppr}");
        last = at;
    }
}

/// Rebuild a package with one part replaced.
fn rewrite_part(docx: &[u8], part: &str, f: impl Fn(&str) -> String) -> Vec<u8> {
    use std::io::{Read, Write};
    let mut z = zip::ZipArchive::new(std::io::Cursor::new(docx)).unwrap();
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        let mut zw = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        for i in 0..z.len() {
            let mut e = z.by_index(i).unwrap();
            let name = e.name().to_string();
            let mut v = Vec::new();
            e.read_to_end(&mut v).unwrap();
            if name == part {
                v = f(&String::from_utf8_lossy(&v)).into_bytes();
            }
            zw.start_file(name, o).unwrap();
            zw.write_all(&v).unwrap();
        }
        zw.finish().unwrap();
    }
    cur.into_inner()
}

// ================================================== conversion-warning cancellation

/// Cancelling the pre-conversion warning must leave nothing behind.
///
/// The dialog lives in the window, so what is asserted here is the invariant it relies on:
/// a job that is never started writes no output and does not touch the source. If cancelling
/// ever did start a job, this is the property that would break.
#[test]
fn c55_a_job_that_is_never_started_writes_nothing_and_touches_nothing() {
    let d = batch_dir("cancelled");
    let out = d.join("cikti");
    let srcs = vec![
        write_docx_file(&d, "Dilekçe.docx"),
        write_udf_file(&d, "Karar.udf"),
    ];
    let before: Vec<String> = srcs
        .iter()
        .map(|p| tavzih_core::convert::sha256_file(p).unwrap())
        .collect();

    // The user pressed Vazgeç: convert_batch_to is simply never called.
    assert!(
        !out.exists(),
        "cancelling must not create the output directory"
    );
    assert_sources_untouched(&srcs, &before);

    // Confirming afterwards still works and is unaffected by the earlier cancellation.
    let r = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2300"));
    assert_eq!(r.failed, 0);
    assert!(r.all_sources_unchanged);
    assert_sources_untouched(&srcs, &before);
    let _ = std::fs::remove_dir_all(&d);
}

/// The output root must resolve on either platform, from the right environment variable.
#[test]
fn c56_output_root_is_platform_correct() {
    let r = tavzih_core::convert::output_root();
    let tail: Vec<String> = r
        .components()
        .rev()
        .take(3)
        .map(|c| c.as_os_str().to_string_lossy().to_string())
        .collect();
    assert_eq!(tail, vec!["Dönüştürülen Belgeler", "Tavzih", "Documents"]);
    assert!(r.is_absolute() || cfg!(test), "{}", r.display());
}

/// Output naming must survive names that are awkward on Windows: Turkish characters,
/// spaces, dots and length.
#[test]
fn c57_awkward_file_names_produce_usable_outputs() {
    let d = batch_dir("names");
    let out = d.join("cikti");
    let long_name = "çok uzun bir dosya adı ".repeat(6) + "son.docx";
    let names = [
        "İstinaf Başvuru Dilekçesi ve Ekleri.docx",
        "Şirket - Ödeme Emri (2026-428) v2.1.docx",
        long_name.as_str(),
    ];
    let mut srcs = Vec::new();
    for n in &names {
        let p = d.join(n.trim());
        std::fs::write(&p, to_docx(&doc(vec![para("içerik")]))).unwrap();
        srcs.push(p);
    }
    let before: Vec<String> = srcs
        .iter()
        .map(|p| tavzih_core::convert::sha256_file(p).unwrap())
        .collect();

    let r = tavzih_core::convert::convert_batch_to(&srcs, &out, Some("2026-08-30_2300"));
    assert_eq!(
        r.failed,
        0,
        "{:?}",
        r.items.iter().map(|i| &i.error).collect::<Vec<_>>()
    );
    let entries = zip_entries(&PathBuf::from(r.output.unwrap()));
    assert_eq!(entries.len(), 3, "{entries:?}");
    assert!(entries.iter().any(|e| e.contains("İstinaf")), "{entries:?}");
    assert!(entries.iter().any(|e| e.contains("Ödeme")), "{entries:?}");
    // No entry may carry a separator that would create an unintended folder.
    for e in &entries {
        assert_eq!(e.matches('/').count(), 1, "unexpected nesting in {e}");
        assert!(!e.contains('\\'), "backslash in ZIP entry {e}");
    }
    assert_sources_untouched(&srcs, &before);
    let _ = std::fs::remove_dir_all(&d);
}

// ---------------------------------------------------------------- hardening: field-code leak (skeptic 3, P1)

/// Ham bir DOCX paketi kur: yalnızca `word/document.xml`. Okuyucu bu tek parçayı
/// zorunlu tutar, gerisi opsiyoneldir (reader.rs `load_package`).
fn raw_docx(document_xml: &str) -> Vec<u8> {
    use std::io::Write;
    let mut cur = std::io::Cursor::new(Vec::new());
    {
        let mut z = zip::ZipWriter::new(&mut cur);
        let o: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        z.start_file("word/document.xml", o).unwrap();
        z.write_all(document_xml.as_bytes()).unwrap();
        z.finish().unwrap();
    }
    cur.into_inner()
}

fn doc_all_text(d: &Document) -> String {
    fn blocks(out: &mut String, bs: &[Block]) {
        for b in bs {
            match b {
                Block::Paragraph(p) => {
                    out.push_str(&p.text());
                    out.push('\n');
                }
                Block::Table(t) => {
                    for r in &t.rows {
                        for c in &r.cells {
                            blocks(out, &c.blocks);
                        }
                    }
                }
                _ => {}
            }
        }
    }
    let mut s = String::new();
    for sec in &d.sections {
        blocks(&mut s, &sec.blocks);
    }
    s
}

/// P1 (skeptic 3): Word'ün "complex field" yapısı `fldChar(begin) → instrText(KOD)
/// → fldChar(separate) → önbelleğe alınmış görünen değer → fldChar(end)` biçimindedir.
/// `instrText` içindeki alan kodu (HYPERLINK hedefi, REF/PAGEREF yer imi, MERGEFIELD
/// veri adı) KULLANICIYA GÖSTERİLMEZ; yalnızca separate'ten sonraki değer gösterilir.
/// Okuyucu instrText metnini bastırmazsa alan kodu gövde metnine sızar — kullanıcı
/// belgesine ait olmayan, hatta gizli olabilecek (iç URL, yer imi) veri Dönüştür
/// çıktısında görünür.
#[test]
fn hardening_complex_field_instruction_codes_never_leak_into_body() {
    let xml = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:r><w:t xml:space="preserve">Görülen: </w:t></w:r>
      <w:r><w:fldChar w:fldCharType="begin"/></w:r>
      <w:r><w:instrText xml:space="preserve"> HYPERLINK "http://ic-sunucu.example/kayit?dava=2026-42&amp;gizli=1" </w:instrText></w:r>
      <w:r><w:fldChar w:fldCharType="separate"/></w:r>
      <w:r><w:t>Ek-3 numaralı belge</w:t></w:r>
      <w:r><w:fldChar w:fldCharType="end"/></w:r>
    </w:p>
    <w:p>
      <w:r><w:t xml:space="preserve">Bakınız </w:t></w:r>
      <w:r><w:fldChar w:fldCharType="begin"/></w:r>
      <w:r><w:instrText xml:space="preserve"> REF _Ref123456 \h </w:instrText></w:r>
      <w:r><w:fldChar w:fldCharType="separate"/></w:r>
      <w:r><w:t>madde 5</w:t></w:r>
      <w:r><w:fldChar w:fldCharType="end"/></w:r>
      <w:r><w:t>.</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:fldChar w:fldCharType="begin"/></w:r>
      <w:r><w:instrText xml:space="preserve"> MERGEFIELD MusteriTCKN </w:instrText></w:r>
      <w:r><w:fldChar w:fldCharType="end"/></w:r>
    </w:p>
  </w:body>
</w:document>"#;
    let (d, warns) = read_docx(&raw_docx(xml));
    let text = doc_all_text(&d);

    // Görünen değerler korunur.
    assert!(text.contains("Görülen: Ek-3 numaralı belge"), "görünen değer kayıp: {text:?}");
    assert!(text.contains("Bakınız madde 5."), "REF görünen değeri kayıp: {text:?}");

    // Alan kodunun HİÇBİR parçası gövdeye sızmamalı.
    for needle in [
        "HYPERLINK",
        "ic-sunucu.example",
        "gizli=1",
        "REF _Ref123456",
        "_Ref123456",
        "MERGEFIELD",
        "MusteriTCKN",
        "\\h",
    ] {
        assert!(
            !text.contains(needle),
            "alan kodu gövde metnine sızdı: {needle:?} in {text:?}"
        );
    }

    // Kayıp sessiz olmamalı: kullanıcı alanların düzleştirildiğini görmeli.
    assert!(
        warns.contains(&WarningCode::FieldFlattened),
        "alan düzleştirme uyarısı verilmedi: {warns:?}"
    );
}
